### ISSUE TITLE
Moss Wand Crashes modpack during startup.

### ISSUE THREAD

**Issue by toErIpNid** [GPeckman/MossWand#1]
Crash Log: 
[crash-2021-07-01_22.43.54-client.txt](https://github.com/GPeckman/MossWand/files/6751969/crash-2021-07-01_22.43.54-client.txt)

MC Version: 1.16.5
Mod Version: 1.2.0
Fabric Version: 0.11.6

**Comment by GPeckman** [comment]
That error message means that you are still using Java 8. The mod was built using Java 16. I'm working on uploading a version built with Java 8, but I'm having difficulties, so it might take a few more days.

**Comment by GPeckman** [comment]
Update: the difficulties have been solved. A hotfix has been uploaded to curseforge.
